# Generated by Django 3.1 on 2020-08-30 18:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('office', '0002_auto_20200830_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='officemodel',
            name='users',
            field=models.ManyToManyField(related_name='offices', to=settings.AUTH_USER_MODEL),
        ),
    ]
